# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

def myPods
  pod 'JBChartView'
end

target 'CalorieTracker' do
  use_frameworks!
  myPods

  # Pods for CalorieTracker

  target 'CalorieTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalorieTrackerUITests' do
    # Pods for testing
  end

end
